services:
  - type: web
    name: personalised-u
    env: node
    buildCommand: npm install && npm run build
    startCommand: ./start.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
    autoDeploy: true
    disk:
      name: next-build
      mountPath: .next
      sizeGB: 1 
