services:
  - type: web
    name: personalised-u
    env: node
    buildCommand: npm install && npm install --save-dev typescript @types/react && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
    autoDeploy: true 
